// Generated by scripts/gen_docs.py from contracts/redline.py. Do not edit by hand.
// The posting form runs the contract's own policy before anything is signed; the
// contract runs it again on chain, so this copy only saves a refused transaction.

/** KEY_PATTERNS: strings shaped like real credentials. */
export const KEY_PATTERNS: RegExp[] = [
  new RegExp("sk-[A-Za-z0-9_\\-]{20,}"),
  new RegExp("AKIA[0-9A-Z]{16}"),
  new RegExp("gh[pousr]_[A-Za-z0-9]{30,}"),
  new RegExp("xox[abprs]-[A-Za-z0-9\\-]{10,}"),
  new RegExp("AIza[0-9A-Za-z_\\-]{35}"),
  new RegExp("-----BEGIN [A-Z ]*PRIVATE KEY-----"),
  new RegExp("\\b(0x)?[0-9a-fA-F]{64}\\b"),
];

/** HARMFUL_WORDS: targets about these need harmful output to break, so they are refused. */
export const HARMFUL_WORDS: string[] = [
  "bioweapon",
  "bomb",
  "bombs",
  "chemical weapon",
  "explosive",
  "explosives",
  "malware",
  "nerve agent",
  "ransomware",
  "self-harm",
  "suicide",
  "terrorist",
  "weapon",
  "weapons",
];

export const CANARY_LENGTH = 12;
export const MAX_ATTACK = 1500;
