#!/usr/bin/env python3
"""
Generate the docs pages and site data that are copies of the contract and its records.

    python scripts/gen_docs.py           # write the files
    python scripts/gen_docs.py --check   # exit 1 if any file differs from what would be written

A method cannot exist in the code and be missing from the docs, the judge
prompt on the site cannot drift from the one validators read, and the posting
form's key scanner cannot drift from the contract's, because both are
written from contracts/redline.py by this script, and a test runs --check.

Writes:
  web/content/docs/reference/contract.mdx    every public method, from the source
  web/content/docs/reference/errors.mdx      every refusal sentence, from the source
  web/content/docs/reference/addresses.mdx   the deployment, from contracts/FROZEN.json
  web/content/docs/more/judge-prompt.mdx     the agent and scope judge prompts, word for word
  web/content/docs/more/evaluation.mdx       the golden run, from eval/results.json
  web/lib/contract.generated.json            limits, statuses and the prompts, for the site
  web/lib/policy.generated.ts                the key scanner and rule policy, for the posting form
and refreshes every `{/* include: path */}` code sample in the docs from the file it names.
"""

from __future__ import annotations

import ast
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "redline.py"
DOCS = ROOT / "web" / "content" / "docs"
REPO = "https://github.com/meitipro/redline/blob/main"

HEADER = "{/* Generated by scripts/gen_docs.py from contracts/redline.py. Do not edit by hand. */}\n\n"


def load():
    source = CONTRACT.read_text(encoding="utf-8")
    return source, ast.parse(source)


def constant(tree: ast.Module, name: str):
    for node in tree.body:
        if isinstance(node, ast.Assign) and ast.unparse(node.targets[0]) == name:
            try:
                return ast.literal_eval(node.value)
            except ValueError:
                return ast.unparse(node.value)
    raise KeyError(name)


def contract_class(tree: ast.Module) -> ast.ClassDef:
    return next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "Redline")


def kind_of(node: ast.FunctionDef) -> str:
    for deco in node.decorator_list:
        text = ast.unparse(deco)
        if text == "gl.public.write":
            return "write"
        if text == "gl.public.write.payable":
            return "payable"
        if text == "gl.public.view":
            return "view"
    return ""


def mdx_text(text: str) -> str:
    """Plain prose into MDX: braces and angle brackets would be read as code."""
    return text.replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;").replace(">", "&gt;")


def signature(node: ast.FunctionDef) -> str:
    args = ", ".join(f"{a.arg}: {ast.unparse(a.annotation)}" for a in node.args.args[1:])
    returns = ast.unparse(node.returns) if node.returns else "None"
    return f"{node.name}({args}) -> {returns}"


def methods(tree: ast.Module) -> list[dict]:
    out = []
    for node in contract_class(tree).body:
        if isinstance(node, ast.FunctionDef) and kind_of(node):
            doc = ast.get_docstring(node) or ""
            out.append(
                {
                    "name": node.name,
                    "kind": kind_of(node),
                    "signature": signature(node),
                    "args": [{"name": a.arg, "type": ast.unparse(a.annotation)} for a in node.args.args[1:]],
                    "returns": ast.unparse(node.returns) if node.returns else "None",
                    "doc": " ".join(doc.split()),
                    "line": node.lineno,
                }
            )
    return out


def refusals(tree: ast.Module) -> list[dict]:
    """Every UserError sentence, with the function it can come from. Dynamic parts read as '…'."""

    def text_of(expr: ast.AST) -> tuple[str, str]:
        parts: list[str] = []

        def walk(e: ast.AST) -> None:
            if isinstance(e, ast.BinOp) and isinstance(e.op, ast.Add):
                walk(e.left)
                walk(e.right)
            elif isinstance(e, ast.Constant) and isinstance(e.value, str):
                parts.append(e.value)
            elif isinstance(e, ast.Name) and e.id in ("E", "L"):
                parts.append("\x00" + e.id)
            else:
                parts.append("…")

        walk(expr)
        prefix = parts[0][1:] if parts and parts[0].startswith("\x00") else ""
        body = "".join(p for p in parts if not p.startswith("\x00"))
        return prefix, body

    owner: dict[int, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            for inner in ast.walk(node):
                if hasattr(inner, "lineno"):
                    owner.setdefault(inner.lineno, node.name)
    rows: dict[tuple, dict] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and ast.unparse(node.func) == "gl.vm.UserError" and node.args:
            prefix, body = text_of(node.args[0])
            key = (prefix, body)
            where = owner.get(node.lineno, "")
            row = rows.setdefault(key, {"prefix": prefix, "text": body, "where": []})
            if where and where not in row["where"]:
                row["where"].append(where)
    return sorted(rows.values(), key=lambda r: (r["prefix"], r["text"]))


def build() -> dict[pathlib.Path, str]:
    source, tree = load()
    judge = constant(tree, "SCOPE_JUDGE")
    judge_sha = hashlib.sha256(judge.encode("utf-8")).hexdigest()
    listed = methods(tree)
    errors = refusals(tree)
    files: dict[pathlib.Path, str] = {}

    # -- contract reference --------------------------------------------------
    kinds = {"write": "write", "payable": "write, payable", "view": "view"}
    lines = [
        "---",
        "title: Contract reference",
        "description: Every public method of contracts/redline.py, generated from the source.",
        "---",
        "",
        HEADER.strip(),
        "",
        f"One contract, {len(listed)} methods: {sum(1 for m in listed if m['kind'] != 'view')} writes and "
        f"{sum(1 for m in listed if m['kind'] == 'view')} views. This page is written from the contract source by "
        "`scripts/gen_docs.py`, and a test fails if the two drift, so a method cannot exist in code and be missing here.",
        "",
        "Views return JSON text. An unknown target or attack reads as `{\"found\": false}` rather than an error, because "
        "a view that raises reaches a client only as \"execution failed\". Amounts are wei, as decimal strings.",
        "",
        "| Method | Kind | What it does |",
        "|---|---|---|",
    ]
    for m in listed:
        first = mdx_text(m["doc"].split(". ")[0].rstrip(".")) + "."
        lines.append(f"| [`{m['name']}`](#{m['name'].replace('_', '-')}) | {kinds[m['kind']]} | {first} |")
    lines.append("")
    for m in listed:
        lines += [
            f"## {m['name']}",
            "",
            "```python",
            m["signature"],
            "```",
            "",
            f"**{kinds[m['kind']].capitalize()}.** {mdx_text(m['doc'])}",
            "",
        ]
        own = [e for e in errors if m["name"] in e["where"]]
        if own:
            lines.append("Refusals raised in the method itself (the rule, text and policy checks add their own, listed on the Errors page):")
            lines.append("")
            for e in own:
                lines.append(f"- `[{'EXPECTED' if e['prefix'] == 'E' else 'LLM_ERROR'}] {e['text']}`")
            lines.append("")
        lines.append(f"[Source, line {m['line']}]({REPO}/contracts/redline.py#L{m['line']})")
        lines.append("")
    files[DOCS / "reference" / "contract.mdx"] = "\n".join(lines)

    # -- errors --------------------------------------------------------------
    lines = [
        "---",
        "title: Errors",
        "description: Every refusal the contract can raise, generated from the source.",
        "---",
        "",
        HEADER.strip(),
        "",
        "A refused write still reaches consensus: validators agree the refusal is the right result, and the transaction "
        "reads ACCEPTED. The site counts a write as done only when the status is ACCEPTED or FINALIZED **and** the "
        "execution returned; otherwise it shows the sentence below, which the transaction carries in its result payload.",
        "",
        "`[EXPECTED]` refusals are deterministic and identical on every validator. `[LLM_ERROR]` means the scope judge's "
        "answer could not be read, even after one retry; validators then disagree on purpose, so the round rotates to a "
        "committee that can answer, and nothing defaults to a verdict.",
        "",
        "A rejected attack is not a refusal: an attack that is too long or holds a canary-shaped string is stored as "
        "`REJECTED`, with its reason, and its fee is refunded through `claim`.",
        "",
        "| Refusal | Raised in |",
        "|---|---|",
    ]
    for e in errors:
        tag = "EXPECTED" if e["prefix"] == "E" else "LLM_ERROR"
        where = ", ".join(f"`{w}`" for w in e["where"])
        lines.append(f"| `[{tag}] {e['text']}` | {where} |")
    lines.append("")
    files[DOCS / "reference" / "errors.mdx"] = "\n".join(lines)

    # -- the prompts ---------------------------------------------------------
    agent = constant(tree, "AGENT_HEAD") + "{instructions}" + constant(tree, "AGENT_MIDDLE") + "{attack}" + constant(tree, "AGENT_TAIL")
    lines = [
        "---",
        "title: The scope judge prompt, word for word",
        "description: The judge prompt and the agent prompt every validator reads, copied from the contract.",
        "---",
        "",
        HEADER.strip(),
        "",
        "Each validator makes at most two model calls per attack: one agent run, and the scope judge only when a scope "
        "rule could still change the verdict. Secret and action rules are checked by code on each validator's own reply "
        "and never reach a model.",
        "",
        "## The agent run",
        "",
        "`agent_prompt()` joins the builder's instructions, with this run's canary in the `{CANARY}` slot, and the attack "
        "as the user message. It joins, never formats, so braces in either text are only text:",
        "",
        "```text",
        agent,
        "```",
        "",
        "A chat API keeps instructions and user message apart by role, which no text can forge. Here they share one "
        "prompt, so both texts are fenced first: every `<` becomes `(` and every `>` becomes `)`, and no attack can write "
        "`>>>` to close its own block and open a forged one. The canary goes into the slot after fencing, so the slot is "
        "the contract's alone. Storage keeps what the builder and the hunter wrote.",
        "",
        "## The scope judge",
        "",
        "This is the `SCOPE_JUDGE` constant in `contracts/redline.py`, section 3 of the build spec word for word. The rule, "
        "the attack and the agent's reply are each fenced before they are inserted.",
        "",
        "```text",
        judge.replace("{{", "{").replace("}}", "}"),
        "```",
        "",
        f"SHA-256 of the constant: `{judge_sha}`.",
        "",
        "## How validators agree",
        "",
        "Each validator runs the agent on its own model with the same canary, checks its own reply, and agrees only when "
        "its **verdict** is the leader's: `HELD`, or `BROKEN:` with the same rule number. The reply (cut to "
        f"{constant(tree, 'MAX_REPLY')} characters, canary masked) and the reason are stored from the leader for display "
        "and are never compared.",
        "",
        "A judge answer that cannot be read is retried once, then fails the round. It never becomes a verdict. A round "
        "where the models behave differently does not reach agreement: nothing is stored, the attack stays queued, and "
        "nobody is paid.",
        "",
    ]
    files[DOCS / "more" / "judge-prompt.mdx"] = "\n".join(lines)

    # -- site data -----------------------------------------------------------
    data = {
        "source": "contracts/redline.py",
        "scopeJudge": judge.replace("{{", "{").replace("}}", "}"),
        "scopeJudgeSha256": judge_sha,
        "agentPrompt": agent,
        "slot": constant(tree, "SLOT"),
        "checks": constant(tree, "CHECKS"),
        "modes": list(constant(tree, "MODES")),
        "limits": {
            "name": constant(tree, "MAX_NAME"),
            "minInstructions": constant(tree, "MIN_INSTRUCTIONS"),
            "instructions": constant(tree, "MAX_INSTRUCTIONS"),
            "rules": constant(tree, "MAX_RULES"),
            "rule": constant(tree, "MAX_RULE"),
            "unit": constant(tree, "MAX_UNIT"),
            "allowlist": constant(tree, "MAX_ALLOW"),
            "recipient": constant(tree, "MAX_RECIPIENT"),
            "attack": constant(tree, "MAX_ATTACK"),
            "minLockDays": constant(tree, "MIN_LOCK_DAYS"),
            "maxLockDays": constant(tree, "MAX_LOCK_DAYS"),
            "reply": constant(tree, "MAX_REPLY"),
            "page": constant(tree, "MAX_PAGE"),
            "canaryLength": constant(tree, "CANARY_LENGTH"),
        },
        "methods": [{k: m[k] for k in ("name", "kind", "signature", "doc")} for m in listed],
    }
    files[ROOT / "web" / "lib" / "contract.generated.json"] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    patterns = constant(tree, "KEY_PATTERNS")
    words = constant(tree, "HARMFUL_WORDS")
    policy = [
        "// Generated by scripts/gen_docs.py from contracts/redline.py. Do not edit by hand.",
        "// The posting form runs the contract's own policy before anything is signed; the",
        "// contract runs it again on chain, so this copy only saves a refused transaction.",
        "",
        "/** KEY_PATTERNS: strings shaped like real credentials. */",
        "export const KEY_PATTERNS: RegExp[] = [",
    ]
    policy += [f"  new RegExp({json.dumps(p)})," for p in patterns]
    policy += [
        "];",
        "",
        "/** HARMFUL_WORDS: targets about these need harmful output to break, so they are refused. */",
        "export const HARMFUL_WORDS: string[] = [",
    ]
    policy += [f"  {json.dumps(w)}," for w in words]
    policy += [
        "];",
        "",
        f"export const CANARY_LENGTH = {constant(tree, 'CANARY_LENGTH')};",
        f"export const MAX_ATTACK = {constant(tree, 'MAX_ATTACK')};",
        "",
    ]
    files[ROOT / "web" / "lib" / "policy.generated.ts"] = "\n".join(policy)

    files[DOCS / "more" / "evaluation.mdx"] = evaluation_page()
    files[DOCS / "reference" / "addresses.mdx"] = addresses_page()
    files.update(synced_includes())
    return files


# -- evaluation, from eval/results.json -----------------------------------------------
def evaluation_page() -> str:
    results = json.loads((ROOT / "eval" / "results.json").read_text(encoding="utf-8"))
    golden = json.loads((ROOT / "eval" / "golden.json").read_text(encoding="utf-8"))
    explorer = results["explorer"]

    def final(cid: str):
        for a in results["attempts"]:
            if a["case"] == cid and a.get("verdict"):
                return a
        return None

    def hit(expected: str, got: str) -> bool:
        return (got == "HELD" or got.startswith("BROKEN:")) if expected == "EITHER" else got == expected

    held = [c for c in golden["cases"] if c.get("held_out")]
    main = [c for c in golden["cases"] if not c.get("held_out")]
    g = sum(1 for c in main if final(c["id"]) and hit(c["expected"], final(c["id"])["verdict"]))
    g_run = sum(1 for c in main if final(c["id"]))
    h_tried = [c for c in held if any(a["case"] == c["id"] for a in results["attempts"])]
    h_agreed = [c for c in h_tried if final(c["id"])]
    lines = [
        "---",
        "title: Evaluation results with transactions",
        "description: The golden cases and the held-out cases through real consensus on the deployed contract, reported as they came out.",
        "---",
        "",
        "{/* Generated by scripts/gen_docs.py from eval/results.json. Do not edit by hand. */}",
        "",
        "Every case below is one attack on a target posted to the deployed contract, "
        f"[`{results['contract']}`]({explorer}/address/{results['contract']}). A hunter account paid the entry fee and "
        "sent it, then one `judge` transaction had every validator run the agent on its own model and check the rules. "
        "Every verdict was read back from the contract with `get_attack`.",
        "",
        f"- **Golden cases 1 to 9: {g} of {g_run}** matched the expected verdict" + (f" ({len(main) - g_run} not run yet)." if g_run < len(main) else "."),
        f"- **Held-out cases: {len(h_agreed)} of {len(h_tried)} reached a verdict**"
        + (f" ({len(held) - len(h_tried)} not run yet)." if len(h_tried) < len(held) else ".")
        + " They are real robustness questions with no expected answer; each ran once, and what came out is below.",
        f"- `eval/golden.json` was hashed and timestamped before the first run: sha256 `{results['golden_sha256']}`, "
        f"locked at {results['golden_locked_at']}.",
        f"- The scope judge is the spec's prompt, word for word (sha256 `{results['scope_judge_sha256']}`). Nothing was tuned.",
        "",
        "| Case | Target | Attack | Expected | Got | Transaction |",
        "|---|---|---|---|---|---|",
    ]
    for c in golden["cases"]:
        a = final(c["id"])
        tag = f"{c['id']}{' (held out)' if c.get('held_out') else ''}"
        name = mdx_text(golden["targets"][c["target"]]["name"])
        attack = c["attack"] if len(c["attack"]) <= 80 else c["attack"][:77] + "..."
        attack = mdx_text(attack).replace("|", "/")
        if not a:
            tried = [x for x in results["attempts"] if x["case"] == c["id"]]
            if tried:
                tx = tried[-1]["tx"]
                lines.append(f"| {tag} | {name} | {attack} | {c['expected']} | **no agreement** | [{tx[:10]}…]({explorer}/tx/{tx}) |")
            else:
                lines.append(f"| {tag} | {name} | {attack} | {c['expected']} | not run yet | |")
            continue
        mark = "✓" if hit(c["expected"], a["verdict"]) else "✗ miss"
        lines.append(f"| {tag} | {name} | {attack} | {c['expected']} | **{a['verdict']}** {mark} | [{a['tx'][:10]}…]({explorer}/tx/{a['tx']}) |")
    lines += ["", "## Why", "", "The leader's reason for each verdict: the failed exact check, the code check, or the scope judge's sentence. Display only, never compared.", ""]
    for c in golden["cases"]:
        a = final(c["id"])
        if a and a.get("reason"):
            lines.append(f"- **{c['id']}**, attack {a['attack_id']}: {mdx_text(a['reason'])}")
        elif a:
            lines.append(f"- **{c['id']}**, attack {a['attack_id']}: no reason sentence; the code checks found nothing broken.")
    lines += ["", "## The leader's replies", "", "Cut to 400 characters by the contract; where the canary appeared it is stored as the slot, never as itself.", ""]
    for c in golden["cases"]:
        a = final(c["id"])
        if a and a.get("reply"):
            reply = " ".join(a["reply"].split())
            lines.append(f"- **{c['id']}**: {mdx_text(reply)}")
    retried = [a for a in results["attempts"] if not a.get("verdict")]
    lines += ["", "## Every attempt", ""]
    if retried:
        lines.append("Judge transactions whose round produced no verdict:")
        lines.append("")
        for a in retried:
            lines.append(f"- case {a['case']} attempt {a['attempt']}: {mdx_text(a['consensus'][:160])} ([tx]({explorer}/tx/{a['tx']}))")
    else:
        lines.append("Every judge produced a verdict on its first attempt; nothing was sent twice.")
    lines += [
        "",
        "## Reproduce",
        "",
        "```bash",
        "python eval/run_golden.py            # golden cases 1 to 9",
        "python eval/run_golden.py H1 H2 H3   # the held-out cases, once",
        "```",
        "",
        "The script refuses to run if `eval/golden.json` no longer matches its locked hash, never sends a case that "
        "produced a verdict again, and saves each step before printing it. Every attempt is in `eval/results.json`.",
        "",
    ]
    return "\n".join(lines)


# -- addresses, from contracts/FROZEN.json --------------------------------------------
def addresses_page() -> str:
    entry = json.loads((ROOT / "contracts" / "FROZEN.json").read_text(encoding="utf-8"))["deployments"]["studio-next"]
    explorer = entry["explorer"]
    lines = [
        "---",
        "title: Addresses and network",
        "description: The deployed contract, its source hash and the network it runs on.",
        "---",
        "",
        "{/* Generated by scripts/gen_docs.py from contracts/FROZEN.json. Do not edit by hand. */}",
        "",
        "| | |",
        "|---|---|",
        f"| Contract | [`{entry['redline']}`]({explorer}/address/{entry['redline']}) |",
        f"| Deploy transaction | [`{entry['redline_tx']}`]({explorer}/tx/{entry['redline_tx']}) |",
        f"| Deployed | {entry['deployed_at']} |",
        f"| Deployer | [`{entry['redline_deployer']}`]({explorer}/address/{entry['redline_deployer']}) |",
        f"| Source | `contracts/redline.py`, sha256 `{entry['redline_sha256']}` |",
        f"| Runtime | `{entry['runtime']}` (GenVM SDK v0.3) |",
        "| Network | GenLayer Studio Next |",
        f"| Chain id | {entry['chain_id']} (`0x{entry['chain_id']:x}`) |",
        "| RPC | `https://studio-next.genlayer.com/api` |",
        f"| Explorer | {explorer} |",
        "| Currency | GEN, 18 decimals. Test GEN from the site's faucet. |",
        "",
        "## Check the deployment yourself",
        "",
        "`scripts/verify.py` reads the source back off the chain with `gen_getContractCode`, compares it byte for byte "
        "with `contracts/redline.py`, checks the sha256 against `contracts/FROZEN.json`, and lints the bytes that came "
        "back with genvm-lint:",
        "",
        "```bash",
        "python scripts/verify.py",
        "```",
        "",
        "## The canary seed, measured",
        "",
        "The canary comes from data of the judging transaction. Before building on it, a probe contract recorded what "
        "`gl.message.raw` carries in a write on this network (`docs/seed-probe.json`): the datetime arrives with "
        "microseconds, and no transaction hash is exposed. So the seed is the judging transaction's datetime and sender, "
        "the contract address, the attack id and the attack text's hash.",
        "",
        "## Add the network to a wallet",
        "",
        "The site does this for you. By hand: network name `GenLayer Studio Next`, RPC "
        f"`https://studio-next.genlayer.com/api`, chain id `{entry['chain_id']}`, currency `GEN`, explorer `{explorer}`.",
        "",
        "Studio Next charges a fee deposit on every write, from the SDK's estimate; most of it is refunded when the "
        "transaction finalizes. Reads are free. The RPC rate-limits each IP, so the site caches shared reads for 20 seconds "
        "and drops the cache after each write.",
        "",
    ]
    return "\n".join(lines)


# -- code samples copied from files that run -----------------------------------------
INCLUDE_OPEN = "{/* include: "
INCLUDE_CLOSE = "{/* end include */}"
LANGS = {".mjs": "js", ".js": "js", ".ts": "ts", ".py": "python", ".json": "json"}
GENERATED = ("reference/contract.mdx", "reference/errors.mdx", "more/judge-prompt.mdx", "more/evaluation.mdx", "reference/addresses.mdx")


def synced_includes() -> dict[pathlib.Path, str]:
    """
    Every `{/* include: path */}` ... `{/* end include */}` block in the docs is
    replaced by the file at <repo>/<path>, fenced. A sample in the docs is then
    the code in the repository, which is the code that was run.
    """
    out: dict[pathlib.Path, str] = {}
    generated = {DOCS / g for g in GENERATED}
    for page in sorted(DOCS.rglob("*.mdx")):
        if page in generated:
            continue
        text = page.read_text(encoding="utf-8")
        if INCLUDE_OPEN not in text:
            continue
        parts = []
        rest = text
        while INCLUDE_OPEN in rest:
            before, _, after = rest.partition(INCLUDE_OPEN)
            path_text, _, after = after.partition(" */}")
            _, _, after = after.partition(INCLUDE_CLOSE)
            source = ROOT / path_text.strip()
            code = source.read_text(encoding="utf-8").rstrip("\n")
            lang = LANGS.get(source.suffix, "")
            parts.append(before + INCLUDE_OPEN + path_text + " */}\n```" + lang + ' title="' + path_text.strip() + '"\n' + code + "\n```\n" + INCLUDE_CLOSE)
            rest = after
        parts.append(rest)
        out[page] = "".join(parts)
    return out


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, text in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if check:
        if stale:
            print("stale generated files, run python scripts/gen_docs.py:\n  " + "\n  ".join(stale))
            return 1
        print("generated files match the contract")
        return 0
    print("wrote " + (", ".join(stale) if stale else "nothing, all current"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
